In [1]:
import pandas as pd

In [3]:
# 2 main datatypes
series = pd.Series(["BMW", "Toyota", "Honda"])

In [4]:
series

0       BMW
1    Toyota
2     Honda
dtype: object

In [5]:
# series is 1-dimensional

In [6]:
colours = pd.Series(["Red","Blue", "White"])
colours

0      Red
1     Blue
2    White
dtype: object

In [7]:
# DataFrame = 2-dimensinal

In [8]:
car_data = pd.DataFrame({"Car make" : series, "Colour": colours})
car_data

  Car make Colour
0      BMW    Red
1   Toyota   Blue
2    Honda  White

In [9]:
# Import Data
car_sales = pd.read_csv("51 - car-sales.csv")

In [10]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [11]:
# Exporting a dataframe
car_sales.to_csv("exported-car-sales.csv", index= False)

In [12]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Describe data

In [13]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [14]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [15]:
car_columns = car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [16]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [17]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [18]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [19]:
car_prices = pd.Series([3000,1500,111250,])
car_prices.mean()

38583.333333333336

In [20]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [21]:
car_sales["Doors"].sum()

40

In [22]:
len(car_sales)

10

## Viewing and selecting data

In [23]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [24]:
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [25]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [26]:
# .loc and .iloc
animals = pd.Series(["cat", "dog", "bird", "pandas", "snake"],
                   index = [0,3,9,8,3])

animals

0       cat
3       dog
9      bird
8    pandas
3     snake
dtype: object

In [27]:
animals.loc[3]

3      dog
3    snake
dtype: object

In [28]:
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [29]:
animals.iloc[3]

'pandas'

In [30]:
animals

0       cat
3       dog
9      bird
8    pandas
3     snake
dtype: object

In [31]:
animals.iloc[:3]

0     cat
3     dog
9    bird
dtype: object

In [32]:
animals.iloc[:3]

0     cat
3     dog
9    bird
dtype: object

In [33]:
car_sales.loc[:3]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [34]:
car_sales["Make"]

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [35]:
car_sales["Colour"]

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6     Blue
7     Blue
8    White
9    White
Name: Colour, dtype: object

In [36]:
car_sales.Make

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [37]:
car_sales[car_sales["Make"] == "Toyota"]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [38]:
car_sales[car_sales["Odometer (KM)"] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00

In [39]:
pd.crosstab(car_sales["Make"], car_sales["Doors"])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [40]:
# groupby
car_sales.groupby(["Make"]).mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
car_sales["Odometer (KM)"].plot()

In [ ]:
car_sales["Odometer (KM)"].hist()

In [ ]:
car_sales["Price"].dtype

In [ ]:
car_sales["Price"] = car_sales["Price"].str.replace(r'[\$,\.]', '', regex=True).astype(int)

In [ ]:
  car_sales["Price"].plot()

## Manipulating Data

In [ ]:
car_sales["Make"].str.lower()

In [ ]:
car_sales["Make"] = car_sales["Make"].str.lower()

In [ ]:
car_sales

In [ ]:
car_sales_missing = pd.read_csv("58 - car-sales-missing-data.csv")
car_sales_missing

In [ ]:
car_sales_missing["Odometer"] = car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean())

In [ ]:
car_sales_missing

In [ ]:
car_sales_missing.dropna()

In [ ]:
car_sales_missing.dropna(inplace = True)

In [41]:
car_sales_missing

NameError: name 'car_sales_missing' is not defined

In [42]:
car_sales_missing = pd.read_csv("58 - car-sales-missing-data.csv")
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [43]:
car_sales_missing_dropped = car_sales_missing.dropna()
car_sales_missing_dropped

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500

In [44]:
car_sales_missing_dropped.to_csv("car-sales-missing-dropped.csv")

In [45]:
import pandas as pd
# Column from series
seats_column = pd.Series([5,5,5,5,5])

# New columns added called seats
car_sales["Seats"] = seats_column
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    NaN
6   Honda   Blue          45698      4   $7,500.00    NaN
7   Honda   Blue          54738      4   $7,000.00    NaN
8  Toyota  White          60000      4   $6,250.00    NaN
9  Nissan  White          31600      4   $9,700.00    NaN

In [46]:
car_sales["Seats"].fillna(5, inplace = True)

C:\Users\MR.CRIMINAL\AppData\Local\Temp\ipykernel_57352\2627188857.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales["Seats"].fillna(5, inplace = True)

In [47]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    5.0
6   Honda   Blue          45698      4   $7,500.00    5.0
7   Honda   Blue          54738      4   $7,000.00    5.0
8  Toyota  White          60000      4   $6,250.00    5.0
9  Nissan  White          31600      4   $9,700.00    5.0

In [53]:
# Column from the python list 
fuel_economy = [7.5, 9.2, 5.0, 9.6, 8.67, 4.7, 4.9,6.4,4.0,4.56]
car_sales["Fuel per 100 KM"]= fuel_economy
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats  Fuel per 100 KM
0  Toyota  White         150043      4   $4,000.00    5.0             7.50
1   Honda    Red          87899      4   $5,000.00    5.0             9.20
2  Toyota   Blue          32549      3   $7,000.00    5.0             5.00
3     BMW  Black          11179      5  $22,000.00    5.0             9.60
4  Nissan  White         213095      4   $3,500.00    5.0             8.67
5  Toyota  Green          99213      4   $4,500.00    5.0             4.70
6   Honda   Blue          45698      4   $7,500.00    5.0             4.90
7   Honda   Blue          54738      4   $7,000.00    5.0             6.40
8  Toyota  White          60000      4   $6,250.00    5.0             4.00
9  Nissan  White          31600      4   $9,700.00    5.0             4.56

In [55]:
# Column from another columns
car_sales["Total fuel used (L)"] = car_sales["Odometer (KM)"]/100 * car_sales["Fuel per 100 KM"] 
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used,Total fuel used (L)
0,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,11253.2250
1,Honda,Red,87899,4,"$5,000.00",5.0,9.20,8086.7080,8086.7080
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.00,1627.4500,1627.4500
3,BMW,Black,11179,5,"$22,000.00",5.0,9.60,1073.1840,1073.1840
4,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,18475.3365
5,Toyota,Green,99213,4,"$4,500.00",5.0,4.70,4663.0110,4663.0110
6,Honda,Blue,45698,4,"$7,500.00",5.0,4.90,2239.2020,2239.2020
7,Honda,Blue,54738,4,"$7,000.00",5.0,6.40,3503.2320,3503.2320
8,Toyota,White,60000,4,"$6,250.00",5.0,4.00,2400.0000,2400.0000
9,Nissan,White,31600,4,"$9,700.00",5.0,4.56,1440.9600,1440.9600

In [56]:
# Create a column from a single values
car_sales["Number of wheels"] = 4
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used,Total fuel used (L),Number of wheels
0,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,11253.2250,4
1,Honda,Red,87899,4,"$5,000.00",5.0,9.20,8086.7080,8086.7080,4
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.00,1627.4500,1627.4500,4
3,BMW,Black,11179,5,"$22,000.00",5.0,9.60,1073.1840,1073.1840,4
4,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,18475.3365,4
5,Toyota,Green,99213,4,"$4,500.00",5.0,4.70,4663.0110,4663.0110,4
6,Honda,Blue,45698,4,"$7,500.00",5.0,4.90,2239.2020,2239.2020,4
7,Honda,Blue,54738,4,"$7,000.00",5.0,6.40,3503.2320,3503.2320,4
8,Toyota,White,60000,4,"$6,250.00",5.0,4.00,2400.0000,2400.0000,4
9,Nissan,White,31600,4,"$9,700.00",5.0,4.56,1440.9600,1440.9600,4

In [57]:
car_sales["Passed road safty"] = True
car_sales.dtypes

Make                    object
Colour                  object
Odometer (KM)            int64
Doors                    int64
Price                   object
Seats                  float64
Fuel per 100 KM        float64
Total fuel used        float64
Total fuel used (L)    float64
Number of wheels         int64
Passed road safty         bool
dtype: object

In [58]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used,Total fuel used (L),Number of wheels,Passed road safty
0,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,11253.2250,4,True
1,Honda,Red,87899,4,"$5,000.00",5.0,9.20,8086.7080,8086.7080,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.00,1627.4500,1627.4500,4,True
3,BMW,Black,11179,5,"$22,000.00",5.0,9.60,1073.1840,1073.1840,4,True
4,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,18475.3365,4,True
5,Toyota,Green,99213,4,"$4,500.00",5.0,4.70,4663.0110,4663.0110,4,True
6,Honda,Blue,45698,4,"$7,500.00",5.0,4.90,2239.2020,2239.2020,4,True
7,Honda,Blue,54738,4,"$7,000.00",5.0,6.40,3503.2320,3503.2320,4,True
8,Toyota,White,60000,4,"$6,250.00",5.0,4.00,2400.0000,2400.0000,4,True
9,Nissan,White,31600,4,"$9,700.00",5.0,4.56,1440.9600,1440.9600,4,True

In [66]:
car_sales = car_sales.drop("Total fuel used", axis = 1)

KeyError: "['Total fuel used'] not found in axis"

In [67]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used (L),Number of wheels,Passed road safty
0,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,4,True
1,Honda,Red,87899,4,"$5,000.00",5.0,9.20,8086.7080,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.00,1627.4500,4,True
3,BMW,Black,11179,5,"$22,000.00",5.0,9.60,1073.1840,4,True
4,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,4,True
5,Toyota,Green,99213,4,"$4,500.00",5.0,4.70,4663.0110,4,True
6,Honda,Blue,45698,4,"$7,500.00",5.0,4.90,2239.2020,4,True
7,Honda,Blue,54738,4,"$7,000.00",5.0,6.40,3503.2320,4,True
8,Toyota,White,60000,4,"$6,250.00",5.0,4.00,2400.0000,4,True
9,Nissan,White,31600,4,"$9,700.00",5.0,4.56,1440.9600,4,True

In [86]:
car_sales_shuffled = car_sales.sample(frac = 1)

In [87]:
car_sales_shuffled

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used (L),Number of wheels,Passed road safty
1,Honda,Red,87899,4,"$5,000.00",5.0,9.20,8086.7080,4,True
0,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,4,True
5,Toyota,Green,99213,4,"$4,500.00",5.0,4.70,4663.0110,4,True
7,Honda,Blue,54738,4,"$7,000.00",5.0,6.40,3503.2320,4,True
6,Honda,Blue,45698,4,"$7,500.00",5.0,4.90,2239.2020,4,True
4,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.00,1627.4500,4,True
9,Nissan,White,31600,4,"$9,700.00",5.0,4.56,1440.9600,4,True
3,BMW,Black,11179,5,"$22,000.00",5.0,9.60,1073.1840,4,True
8,Toyota,White,60000,4,"$6,250.00",5.0,4.00,2400.0000,4,True

In [88]:
# only select 20% of data 
car_sales_shuffled.sample(frac = 0.2)

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used (L),Number of wheels,Passed road safty
0,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,4,True
4,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,4,True

In [89]:
car_sales_shuffled.reset_index(drop = True , inplace = True)

In [90]:
car_sales_shuffled

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used (L),Number of wheels,Passed road safty
0,Honda,Red,87899,4,"$5,000.00",5.0,9.20,8086.7080,4,True
1,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,4,True
2,Toyota,Green,99213,4,"$4,500.00",5.0,4.70,4663.0110,4,True
3,Honda,Blue,54738,4,"$7,000.00",5.0,6.40,3503.2320,4,True
4,Honda,Blue,45698,4,"$7,500.00",5.0,4.90,2239.2020,4,True
5,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,4,True
6,Toyota,Blue,32549,3,"$7,000.00",5.0,5.00,1627.4500,4,True
7,Nissan,White,31600,4,"$9,700.00",5.0,4.56,1440.9600,4,True
8,BMW,Black,11179,5,"$22,000.00",5.0,9.60,1073.1840,4,True
9,Toyota,White,60000,4,"$6,250.00",5.0,4.00,2400.0000,4,True

In [91]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used (L),Number of wheels,Passed road safty
0,Toyota,White,150043,4,"$4,000.00",5.0,7.50,11253.2250,4,True
1,Honda,Red,87899,4,"$5,000.00",5.0,9.20,8086.7080,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.00,1627.4500,4,True
3,BMW,Black,11179,5,"$22,000.00",5.0,9.60,1073.1840,4,True
4,Nissan,White,213095,4,"$3,500.00",5.0,8.67,18475.3365,4,True
5,Toyota,Green,99213,4,"$4,500.00",5.0,4.70,4663.0110,4,True
6,Honda,Blue,45698,4,"$7,500.00",5.0,4.90,2239.2020,4,True
7,Honda,Blue,54738,4,"$7,000.00",5.0,6.40,3503.2320,4,True
8,Toyota,White,60000,4,"$6,250.00",5.0,4.00,2400.0000,4,True
9,Nissan,White,31600,4,"$9,700.00",5.0,4.56,1440.9600,4,True

In [92]:
car_sales["Odometer (KM)"] = car_sales["Odometer (KM)"].apply(lambda x:x/1.6)
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel per 100 KM,Total fuel used (L),Number of wheels,Passed road safty
0,Toyota,White,93776.875,4,"$4,000.00",5.0,7.50,11253.2250,4,True
1,Honda,Red,54936.875,4,"$5,000.00",5.0,9.20,8086.7080,4,True
2,Toyota,Blue,20343.125,3,"$7,000.00",5.0,5.00,1627.4500,4,True
3,BMW,Black,6986.875,5,"$22,000.00",5.0,9.60,1073.1840,4,True
4,Nissan,White,133184.375,4,"$3,500.00",5.0,8.67,18475.3365,4,True
5,Toyota,Green,62008.125,4,"$4,500.00",5.0,4.70,4663.0110,4,True
6,Honda,Blue,28561.250,4,"$7,500.00",5.0,4.90,2239.2020,4,True
7,Honda,Blue,34211.250,4,"$7,000.00",5.0,6.40,3503.2320,4,True
8,Toyota,White,37500.000,4,"$6,250.00",5.0,4.00,2400.0000,4,True
9,Nissan,White,19750.000,4,"$9,700.00",5.0,4.56,1440.9600,4,True